@startuml
actor        developer
control configsvc

database    postgres
database    clichouse
queue       "Schema Registry"        as sr
control     openmetadata
actor        user

developer -> configsvc
configsvc -> postgres: dml
configsvc -> sr
configsvc -> clichouse
configsvc -> openmetadata
openmetadata-> user
@enduml
